import dataplatform
CredentialProvider = dataplatform.credentials.CredentialProvider
TokenProvider = dataplatform.credentials.TokenProvider
OAuthClientCredentials = dataplatform.credentials.OAuthClientCredentials